# Generated by Django 3.2.5 on 2021-07-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0002_remove_magazzino_econtact'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazzino',
            name='edescription',
            field=models.TextField(blank=True),
        ),
    ]
