# Generated by Django 3.2.5 on 2021-07-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0003_magazzino_edescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazzino',
            name='subkey',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
