# Generated by Django 3.2.5 on 2021-07-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0004_magazzino_subkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magazzino',
            name='eefirm',
        ),
        migrations.AddField(
            model_name='magazzino',
            name='code_maker',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='magazzino',
            name='code_vendor',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='magazzino',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='magazzino',
            name='ename',
            field=models.CharField(max_length=50),
        ),
    ]
