# Generated by Django 3.2.5 on 2021-07-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0005_auto_20210706_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazzino',
            name='progetto',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
